### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by wwood** [bioforensics/pytaxonkit#31]
Hi,

Thanks for a useful tool - I find myself wanting to cite pytaxonkit - what do you suggest? I'm also citing taxonkit itself, just curious aout the bindings.
ta

**Comment by standage** [comment]
Thanks for the note! I don't have any immediate plans for formally publishing pytaxonkit, so citing the GitHub repo is probably your best bet for now. Best wishes!

**Comment by wwood** [comment]
It might be helpful to provide a DOI for citing the GitHub along these lines https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

And thanks for the useful tool.

**Comment by standage** [comment]
A new version was released a few days ago. I have deposited this in the OSF archive and accessioned a DOI for citation.
